spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:postgresql://ep-wild-dew-alrdtomd-pooler.c-3.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Gkx6IMmdQe5N&sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect