spring.application.name=ecommerce-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=your_password_here

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true